Repository UWPCE-PythonCert-ClassRepos/SP_2019_210A_classroom, pull requests merged in 2019-04, with the labels that each got.

#20 another
  students/JasneetChandok/Lesson01/breakme.py
Labels: Needs More Done

#27 Test submission Breakme
  students/FredB/session01/breakme.py
  students/FredB/session01/warmups.py
Labels: Needs More Done

#35 adding lesson01 break me file
  students/BrianB/lesson01/break_me.py
  students/BrianB/lesson01/sum_double.py
Labels: Needs More Done

#48 Added sum_series()
  students/ArchWu/Session1/.vscode/settings.json
  students/ArchWu/Session1/break_me.py
  students/ArchWu/Session2/.vscode/settings.json
  students/ArchWu/Session2/Grid_printer.py
  students/ArchWu/Session2/fizzbuzz.py
  students/ArchWu/Session2/series.py
Labels: Needs More Done

#55 Adding session02 code
  students/BrianE/session02/FizzBuzz.py
  students/BrianE/session02/GridPrinter.py
  students/BrianE/session02/series.py
Labels: Needs More Done

#58 adding more test variants to enumerate the implicit and explicit call…
  students/JoeNunnelley/session02/series.py
Labels: Needs More Done

#43 grid print exercise, test passed
  students/Lincoln_Zhang/Session2/fizzbuzz.py
  students/Lincoln_Zhang/Session2/grid_print.py
  students/Lincoln_Zhang/Session2/series.py
Labels: Needs More Done

#49 Added grid1.py
  students/RimleeT/lesson02/grid1.py
Labels: Needs More Done

#50 Adds grid_printer and breakme from jsward
  students/jsward/session01/break_me.py
  students/jsward/session02/fizz_buzz.py
  students/jsward/session02/grid_printer.py
  students/jsward/session02/series.py
Labels: Needs More Done

#57 series ex. complete
  students/JasneetChandok/Lesson02/series.py
Labels: Needs More Done

#56 Lesson 02 Assignment
  students/AndrewMiotke/session02/FizzBuzz.py
  students/AndrewMiotke/session02/Notes/Documentation.md
  students/AndrewMiotke/session02/Notes/basic_python_notes.md
  students/AndrewMiotke/session02/Notes/more_on_functions.md
  students/AndrewMiotke/session02/basic_python_and_functions.py
  students/AndrewMiotke/session02/grid_printer.py
  students/AndrewMiotke/session02/series.py
Labels: Needs More Done

#51 grid file in class
  students/ColeP/Session01/break_me.py
  students/ColeP/Session01/pushups.py
  students/ColeP/Session02/fib.py
  students/ColeP/Session02/fizzbuzz.py
  students/ColeP/Session02/grid_print.py
Labels: Needs More Done

#54 Lesson 02 finished
  students/GKim/lesson02/fizz_buzz.py
  students/GKim/lesson02/grid_printer.py
  students/GKim/lesson02/series.py
  students/GKim/lesson03/list_lab.py
  students/GKim/lesson03/slicing_lab.py
Labels: Needs More Done

#63 Lesson 2
  students/charlie_england/readme.txt
  students/charlie_england/session02/fizz_buzz.py
  students/charlie_england/session02/grid_printer.py
  students/charlie_england/session02/series.py
Labels: Merge Conflict

#72 session03 work
  students/JoeNunnelley/session03/list_lab.py
  students/JoeNunnelley/session03/mailroom.py
  students/JoeNunnelley/session03/slicing_lab.py
  students/JoeNunnelley/session03/string_formatting.py
Labels: Needs More Review

#90 string lab and mailroom
  students/roviram/Lesson03/mail_room.py
  students/roviram/Lesson03/strformat_lab.py
Labels: Needs More Done
